# Generated by Django 5.2.10 on 2026-05-08 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, help_text='Reason for rejection if status is REJECTED', max_length=255, null=True)),
                ('matching_score', models.FloatField(default=0.0, help_text='Algorithm score used for ranking (0-100)')),
                ('proximity_score', models.FloatField(default=0.0, help_text='Proximity component (40% weight)')),
                ('availability_score', models.FloatField(default=0.0, help_text='Availability component (25% weight)')),
                ('specialization_score', models.FloatField(default=0.0, help_text='Specialization component (20% weight)')),
                ('rating_score', models.FloatField(default=0.0, help_text='Rating component (10% weight)')),
                ('performance_score', models.FloatField(default=0.0, help_text='Performance component (5% weight)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='bookings.booking')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispatch_joboffer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='dispatch_jo_booking_25b1f2_idx'), models.Index(fields=['mechanic', 'status'], name='dispatch_jo_mechani_f7e8ce_idx'), models.Index(fields=['expires_at'], name='dispatch_jo_expires_b7911b_idx'), models.Index(fields=['-created_at'], name='dispatch_jo_created_bbc17a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MechanicAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_round', models.IntegerField(default=1, help_text='Attempt number (1st, 2nd, 3rd choice, etc.)')),
                ('available_mechanics_count', models.IntegerField(default=0, help_text='Total mechanics available in city')),
                ('top_mechanics_considered', models.IntegerField(default=3, help_text='Number of top candidates evaluated')),
                ('algorithm_version', models.CharField(default='v1.0', max_length=20)),
                ('algorithm_params', models.JSONField(default=dict, help_text='Algorithm weights and parameters used')),
                ('assignment_result', models.CharField(choices=[('SUCCESS', 'Mechanic Assigned Successfully'), ('ACCEPTANCE_PENDING', 'Awaiting Mechanic Response'), ('REJECTION', 'Mechanic Rejected'), ('EXPIRY', 'Offer Expired'), ('NO_AVAILABLE_MECHANICS', 'No Available Mechanics')], default='ACCEPTANCE_PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history_received', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='bookings.booking')),
            ],
            options={
                'db_table': 'dispatch_mechanicassignmenthistory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'assignment_round'], name='dispatch_me_booking_b83c98_idx'), models.Index(fields=['assigned_mechanic', '-created_at'], name='dispatch_me_assigne_79ab25_idx')],
            },
        ),
    ]
