[pytest]
DJANGO_SETTINGS_MODULE = mobilemechanic.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -p no:warnings
testpaths = users/tests services
markers =
    concurrency: marks tests as concurrency tests (SQLite can't handle these)
    django_db: use django database
