# Generated by Django 5.2.10 on 2026-05-08 05:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "services",
            "0002_serviceavailability_mechanicservicespecialty_servicepromotion",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONFIRMATION", "Pending Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("MECHANIC_ASSIGNED", "Mechanic Assigned"),
                            ("MECHANIC_ACCEPTED", "Mechanic Accepted"),
                            ("MECHANIC_REJECTED", "Mechanic Rejected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("RATED", "Rated"),
                            ("UNRATED", "Unrated"),
                        ],
                        default="PENDING_CONFIRMATION",
                        max_length=20,
                    ),
                ),
                (
                    "service_location",
                    models.CharField(help_text="Address for service", max_length=255),
                ),
                ("city", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Duration in minutes"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, help_text="Actual start time", null=True
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="Actual end time", null=True
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "surge_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.0"), max_digits=3
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("JAZZCASH", "JazzCash"),
                            ("EASYPAISA", "Easypaisa"),
                            ("CARD", "Credit/Debit Card"),
                            ("CASH", "Cash on Completion"),
                            ("WALLET", "Wallet Balance"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CUSTOMER_REQUEST", "Customer Request"),
                            ("MECHANIC_CANCELLED", "Mechanic Cancelled"),
                            ("SYSTEM_AUTO", "System Auto-cancelled"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("NO_MECHANIC_AVAILABLE", "No Mechanic Available"),
                            ("OTHER", "Other Reason"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("MECHANIC", "Mechanic"),
                            ("SYSTEM", "System"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("cancellation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_notes",
                    models.TextField(
                        blank=True, help_text="Reason details for cancellation"
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Customer instructions/notes for the service",
                    ),
                ),
                (
                    "mechanic_notes",
                    models.TextField(
                        blank=True, help_text="Mechanic notes on completion"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_as_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mechanic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned mechanic, can be null initially",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_as_mechanic",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingAddOn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_services",
                    models.ManyToManyField(blank=True, to="services.service"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookingAddOnAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price_at_booking",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Whether this add-on was performed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "add_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="bookings.bookingaddon",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_ons",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONFIRMATION", "Pending Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("MECHANIC_ASSIGNED", "Mechanic Assigned"),
                            ("MECHANIC_ACCEPTED", "Mechanic Accepted"),
                            ("MECHANIC_REJECTED", "Mechanic Rejected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("RATED", "Rated"),
                            ("UNRATED", "Unrated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONFIRMATION", "Pending Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("MECHANIC_ASSIGNED", "Mechanic Assigned"),
                            ("MECHANIC_ACCEPTED", "Mechanic Accepted"),
                            ("MECHANIC_REJECTED", "Mechanic Rejected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("RATED", "Rated"),
                            ("UNRATED", "Unrated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for status change"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="bookings.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="User who made the status change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer", "status"], name="bookings_bo_custome_0cbf77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["mechanic", "status"], name="bookings_bo_mechani_77791c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="bookings_bo_status_b26418_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["city", "scheduled_date"], name="bookings_bo_city_5afaa5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookingaddonassignment",
            unique_together={("booking", "add_on")},
        ),
        migrations.AddIndex(
            model_name="bookingstatushistory",
            index=models.Index(
                fields=["booking", "changed_at"], name="bookings_bo_booking_31aeed_idx"
            ),
        ),
    ]
