# Generated by Django 5.2.10 on 2026-05-08 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAccuracy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('GPS', 'GPS'), ('NETWORK', 'Network-based'), ('FUSED', 'Fused Location Provider')], default='FUSED', max_length=50)),
                ('horizontal_accuracy', models.FloatField(help_text='Horizontal accuracy in meters')),
                ('vertical_accuracy', models.FloatField(blank=True, help_text='Vertical accuracy (elevation) in meters', null=True)),
                ('bearing_accuracy', models.FloatField(blank=True, help_text='Bearing accuracy in degrees', null=True)),
                ('is_from_mock_provider', models.BooleanField(default=False, help_text='Flag for mock location detection')),
                ('satellites_used', models.IntegerField(blank=True, help_text='Number of GPS satellites used', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_accuracy_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracking_locationaccuracy',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['mechanic', '-recorded_at'], name='tracking_lo_mechani_508948_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_json', models.JSONField(blank=True, default=dict, help_text='JSON storage for geographic point: {"lat": x, "lng": y}')),
                ('accuracy', models.IntegerField(default=10, help_text='GPS accuracy in meters')),
                ('speed', models.FloatField(default=0.0, help_text='Speed in km/h at this point')),
                ('estimated_time_arrival', models.DateTimeField(blank=True, help_text='ETA calculated at this location update', null=True)),
                ('event_type', models.CharField(choices=[('DEPARTURE', 'Mechanic Started Travel'), ('UPDATE', 'Periodic Location Update'), ('ARRIVAL', 'Mechanic Arrived at Location'), ('PAUSE', 'Mechanic Paused'), ('RESUME', 'Mechanic Resumed Travel')], default='UPDATE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='bookings.booking')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracking_locationhistory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', '-created_at'], name='tracking_lo_booking_740529_idx'), models.Index(fields=['mechanic', '-created_at'], name='tracking_lo_mechani_34dabd_idx'), models.Index(fields=['-created_at'], name='tracking_lo_created_a5b743_idx')],
            },
        ),
        migrations.CreateModel(
            name='MechanicLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_json', models.JSONField(blank=True, default=dict, help_text='JSON storage for geographic point: {"lat": x, "lng": y}')),
                ('accuracy', models.IntegerField(default=10, help_text='GPS accuracy in meters')),
                ('speed', models.FloatField(default=0.0, help_text='Current speed in km/h')),
                ('estimated_time_arrival', models.DateTimeField(blank=True, help_text='Calculated ETA to service location', null=True)),
                ('distance_to_destination', models.FloatField(default=0.0, help_text='Distance to booking location in km')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sharing', models.BooleanField(default=False, help_text='Whether mechanic is actively sharing location')),
                ('last_pinged_at', models.DateTimeField(blank=True, help_text='Last time location was received (for health checks)', null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_locations', to='bookings.booking')),
                ('mechanic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracking_mechaniclocation',
                'indexes': [models.Index(fields=['mechanic', 'booking'], name='tracking_me_mechani_d0a1cc_idx'), models.Index(fields=['-last_updated'], name='tracking_me_last_up_086fc6_idx')],
            },
        ),
    ]
