"""
Django settings for mobilemechanic project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import unquote, urlparse
import os
import sys

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _csv_config(name, default):
    return [item.strip() for item in config(name, default=default).split(',') if item.strip()]


def _database_config():
    database_url = config('DATABASE_URL', default='')

    if database_url:
        parsed = urlparse(database_url)
        engine_map = {
            'postgres': 'django.db.backends.postgresql',
            'postgresql': 'django.db.backends.postgresql',
            'postgresql_psycopg2': 'django.db.backends.postgresql',
            'mysql': 'django.db.backends.mysql',
            'sqlite': 'django.db.backends.sqlite3',
            'sqlite3': 'django.db.backends.sqlite3',
        }
        engine = engine_map.get(parsed.scheme, 'django.db.backends.postgresql')

        if engine == 'django.db.backends.sqlite3':
            sqlite_name = parsed.path.lstrip('/') or ':memory:'
            if sqlite_name != ':memory:':
                sqlite_name = unquote(sqlite_name)
            return {
                'ENGINE': engine,
                'NAME': sqlite_name,
                'OPTIONS': {
                    'timeout': 30,
                    'isolation_level': None,
                },
                'CONN_MAX_AGE': 0,
                'ATOMIC_REQUESTS': False,
            }

        return {
            'ENGINE': engine,
            'NAME': unquote(parsed.path.lstrip('/')),
            'USER': unquote(parsed.username or ''),
            'PASSWORD': unquote(parsed.password or ''),
            'HOST': parsed.hostname or '',
            'PORT': parsed.port or '',
            'CONN_MAX_AGE': 60,
            'ATOMIC_REQUESTS': False,
        }

    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,
            'isolation_level': None,
        },
        'CONN_MAX_AGE': 0,
        'ATOMIC_REQUESTS': False,
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=False)

ALLOWED_HOSTS = _csv_config('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver')

# ============================================================================
# Dynamic ALLOWED_HOSTS from file
# This allows adding hosts on the droplet without changing source-controlled files.
# File path: <BASE_DIR>/dynamic_allowed_hosts.txt -- one host per line
# ============================================================================
_DYNAMIC_ALLOWED_HOSTS_FILE = BASE_DIR / 'dynamic_allowed_hosts.txt'
if _DYNAMIC_ALLOWED_HOSTS_FILE.exists():
    try:
        with open(_DYNAMIC_ALLOWED_HOSTS_FILE, 'r') as _f:
            for _line in _f:
                _h = _line.strip()
                if _h and _h not in ALLOWED_HOSTS:
                    ALLOWED_HOSTS.append(_h)
    except Exception:
        # Don't crash the app if file read fails; log later if needed
        pass


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    
    # Allauth - Social Authentication
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # DRF Auth
    'dj_rest_auth',
    'dj_rest_auth.registration',
    
    # Custom apps
    'users',
    'services',  # service app created after users
    'bookings',  # TODO: Create after auth module is complete
    'payments',  # Payment processing and invoices
    'dispatch',  # Job assignment and dispatch system
    'tracking',  # Real-time location tracking
    'ratings',  # Booking reviews and ratings
    'notifications',  # Multi-channel notifications
    'mechanics',  # Mechanic onboarding and job management
    'analytics',  # Admin analytics and reporting
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mobilemechanic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mobilemechanic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': _database_config(),
}

# Test database configuration
if 'test' in sys.argv:
    DATABASES['default']['NAME'] = ':memory:'  # Use in-memory DB for tests
    DATABASES['default']['OPTIONS']['isolation_level'] = None


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# See AUTHENTICATION PASSWORD VALIDATORS section below


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================================
REST_FRAMEWORK = {
    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    
    # Permissions
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50,
    'MAX_PAGE_SIZE': 100,
    
    # Filtering and Search
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    
    # Renderers
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    
    # Parsers
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    
    # Throttling (disabled for testing)
    'DEFAULT_THROTTLE_CLASSES': [] if ('test' in sys.argv or 'pytest' in sys.modules) else [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    
    # DateTime Format
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
    
    # Exception Handler
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# ============================================================================
# CORS CONFIGURATION
# ============================================================================
CORS_ALLOWED_ORIGINS = _csv_config(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://localhost:3001,http://localhost:5173,http://localhost:5174,http://localhost:8000,http://localhost:8080,http://localhost:8081,http://127.0.0.1:3000,http://127.0.0.1:3001,http://127.0.0.1:5173,http://127.0.0.1:8080,http://127.0.0.1:8081',
)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================================================
# CUSTOM USER MODEL
# ============================================================================
AUTH_USER_MODEL = 'users.User'

# ============================================================================
# DJANGO SITES FRAMEWORK (Required for allauth)
# ============================================================================
SITE_ID = 1

# ============================================================================
# ALLAUTH CONFIGURATION (Social Authentication)
# ============================================================================
ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Can be 'none', 'optional', or 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False

# When using a custom User model without a username field, tell allauth
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'

# Google OAuth Settings (from environment variables)
from decouple import config

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'FIELDS': {
            'id': 'sub',
            'name': 'name',
            'given_name': 'given_name',
            'family_name': 'family_name',
            'picture': 'picture',
            'email': 'email',
        }
    }
}

# ============================================================================
# AUTHENTICATION BACKENDS
# ============================================================================
AUTHENTICATION_BACKENDS = [
    # Django default
    'django.contrib.auth.backends.ModelBackend',
    
    # Allauth social authentication
    'allauth.account.auth_backends.AuthenticationBackend',
]
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400 * 7  # 7 days
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', cast=bool, default=not DEBUG)
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = False

# ============================================================================
# AUTHENTICATION PASSWORD VALIDATORS
# ============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', cast=int, default=587)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=True)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@mobilemechanic.com')

# Webhook email forwarding (e.g., n8n)
EMAIL_USE_WEBHOOK = config('EMAIL_USE_WEBHOOK', cast=bool, default=True)
EMAIL_WEBHOOK_URL = config('EMAIL_WEBHOOK_URL', default='')

# If webhook usage is enabled and URL provided, use the WebhookEmailBackend
if EMAIL_USE_WEBHOOK and EMAIL_WEBHOOK_URL:
    EMAIL_BACKEND = 'mobilemechanic.email_backend.WebhookEmailBackend'
SERVER_EMAIL = config('SERVER_EMAIL', default='server@mobilemechanic.com')

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# ============================================================================
# CACHE CONFIGURATION
# ============================================================================
CACHE_URL = config('CACHE_URL', default='')

if CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': CACHE_URL,
            'TIMEOUT': 300,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'mobilemechanic-cache',
            'TIMEOUT': 300,  # 5 minutes
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

# ============================================================================
# SECURITY CONFIGURATION
# ============================================================================
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', cast=bool, default=not DEBUG)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', cast=int, default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # Set to True in production
SECURE_HSTS_PRELOAD = False  # Set to True in production

# CSRF Settings
CSRF_COOKIE_SECURE = False  # Set to True in production
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = _csv_config(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:3000,http://localhost:3001,http://localhost:8000',
)

# ============================================================================
# FILE UPLOAD CONFIGURATION
# ============================================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB

# ============================================================================
# STATIC FILES
# ============================================================================
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ============================================================================
# OTP CONFIGURATION
# ============================================================================
OTP_EXPIRY_MINUTES = 5
OTP_LENGTH = 6
MAX_OTP_ATTEMPTS = 3
OTP_RESEND_TIMEOUT = 30  # seconds

# ============================================================================
# RATE LIMITING CONFIGURATION
# ============================================================================
RATE_LIMIT_LOGIN_ATTEMPTS = 5
RATE_LIMIT_SIGNUP_ATTEMPTS = 3
RATE_LIMIT_OTP_SEND = 3
RATE_LIMIT_BLOCK_DURATION = 900  # 15 minutes in seconds

# ============================================================================
# MFA CONFIGURATION
# ============================================================================
MFA_TOTP_ISSUER = 'MobileMechanic'
MFA_TOTP_NAME = 'MobileMechanic'

# ============================================================================
# CUSTOM SETTINGS
# ============================================================================
PROJECT_NAME = 'MobileMechanic'
PROJECT_VERSION = '1.0.0'
API_PREFIX = '/api/v1'

# ============================================================================
# STRIPE PAYMENT CONFIGURATION
# ============================================================================
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
STRIPE_CURRENCY = config('STRIPE_CURRENCY', default='usd')
STRIPE_SUCCESS_URL = config('STRIPE_SUCCESS_URL', default='http://localhost:3000/payment/success')
STRIPE_CANCEL_URL = config('STRIPE_CANCEL_URL', default='http://localhost:3000/payment/cancel')
FRONTEND_URL = 'http://localhost:3000'  # Update for production
TIME_ZONE = 'Asia/Karachi'

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)
