# Generated by Django 5.2.10 on 2026-05-08 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_rating', models.PositiveSmallIntegerField()),
                ('mechanic_rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_reviews', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings_bookingreview',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['booking'], name='ratings_boo_booking_44bbc6_idx'), models.Index(fields=['customer', '-reviewed_at'], name='ratings_boo_custome_f16835_idx'), models.Index(fields=['mechanic', '-reviewed_at'], name='ratings_boo_mechani_b1dc28_idx'), models.Index(fields=['is_verified', '-reviewed_at'], name='ratings_boo_is_veri_57b3ea_idx')],
            },
        ),
    ]
