# Generated by Django 5.2.10 on 2026-05-08 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('service_area_city', models.CharField(blank=True, max_length=150)),
                ('service_radius_km', models.PositiveIntegerField(default=25)),
                ('max_concurrent_jobs', models.PositiveIntegerField(default=3)),
                ('current_active_jobs', models.PositiveIntegerField(default=0)),
                ('current_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mechanics_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MechanicDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CNIC', 'CNIC'), ('LICENSE', 'License'), ('CERTIFICATION', 'Certification'), ('INSURANCE', 'Insurance')], max_length=20)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='mechanic_docs/')),
                ('document_name', models.CharField(blank=True, max_length=150)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mechanics.mechanicprofile')),
            ],
            options={
                'db_table': 'mechanics_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MechanicVacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='mechanics.mechanicprofile')),
            ],
            options={
                'db_table': 'mechanics_vacation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MechanicJobPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], default='BEFORE', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_photos', to='bookings.booking')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mechanics_jobphoto',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'photo_type'], name='mechanics_j_booking_6fdc99_idx'), models.Index(fields=['mechanic', '-created_at'], name='mechanics_j_mechani_cc1c43_idx')],
            },
        ),
        migrations.CreateModel(
            name='MechanicAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='mechanics.mechanicprofile')),
            ],
            options={
                'db_table': 'mechanics_availability',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('mechanic', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
