# Generated by Django 5.2.10 on 2026-05-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
